# Generated by Django 3.1 on 2021-03-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_data', models.JSONField(default='{}')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
