# Generated by Django 3.1 on 2021-05-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=254, verbose_name='검색한지역')),
                ('estate_data', models.JSONField(blank=True, null=True, verbose_name='부동산정보')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=254, verbose_name='주식이름')),
                ('detail_data', models.JSONField(blank=True, null=True, verbose_name='주식트랜드')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
        ),
        migrations.CreateModel(
            name='StockTrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sosok', models.CharField(max_length=254, verbose_name='코스피 / 코스닥')),
                ('page', models.IntegerField(verbose_name='페이지수')),
                ('trend_data', models.JSONField(blank=True, null=True, verbose_name='주식트랜드')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
        ),
    ]
