# Generated by Django 3.1 on 2021-03-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='estate_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
