# Generated by Django 3.1 on 2021-03-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_auto_20210331_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='location',
            field=models.CharField(default='지역', max_length=254, verbose_name='검색한지역'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성시간'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='estate_data',
            field=models.JSONField(blank=True, null=True, verbose_name='부동산정보'),
        ),
    ]
