# Generated by Django 3.1 on 2021-03-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0003_auto_20210331_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='location',
            field=models.CharField(max_length=254, verbose_name='검색한지역'),
        ),
    ]
