# Generated by Django 3.1 on 2021-03-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0004_auto_20210331_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정시간'),
        ),
    ]
