# Generated by Django 3.1 on 2021-03-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0005_estate_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_kind', models.CharField(max_length=254, verbose_name='코스피 / 코스닥')),
                ('trend_page', models.IntegerField(verbose_name='페이지수')),
                ('trend_data', models.JSONField(blank=True, null=True, verbose_name='주식트랜드')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
        ),
    ]
