# Generated by Django 3.1 on 2021-04-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0007_auto_20210331_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=254, verbose_name='주식이름')),
                ('stock_image', models.ImageField(upload_to='', verbose_name='주식 분석 그래프')),
                ('detail_data', models.JSONField(blank=True, null=True, verbose_name='주식트랜드')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
        ),
    ]
