# Generated by Django 3.1 on 2021-04-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0008_stockdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdetail',
            name='stock_image',
        ),
    ]
