# Generated by Django 3.1 on 2021-04-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='use_count',
            field=models.IntegerField(default=0, null=True, verbose_name='사용횟수'),
        ),
    ]
